// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvvNqManYwho_dYQuNhKt_dhe1Wq5YPtk',
    appId: '1:240849414647:web:f7083968df4fa9011ca6f2',
    messagingSenderId: '240849414647',
    projectId: 'shipdetection-28c56',
    authDomain: 'shipdetection-28c56.firebaseapp.com',
    storageBucket: 'shipdetection-28c56.firebasestorage.app',
    measurementId: 'G-J0LC76NMTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMR8_6yajeVWQZyv0owVhBD4iD5EvjcnQ',
    appId: '1:240849414647:android:0a08493c996412ae1ca6f2',
    messagingSenderId: '240849414647',
    projectId: 'shipdetection-28c56',
    storageBucket: 'shipdetection-28c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVR2Hiw9JggnkFJw3cOMH9HWtKD90U8c',
    appId: '1:240849414647:ios:a50bf37c92b14bdc1ca6f2',
    messagingSenderId: '240849414647',
    projectId: 'shipdetection-28c56',
    storageBucket: 'shipdetection-28c56.firebasestorage.app',
    iosBundleId: 'com.example.shipDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaVR2Hiw9JggnkFJw3cOMH9HWtKD90U8c',
    appId: '1:240849414647:ios:a50bf37c92b14bdc1ca6f2',
    messagingSenderId: '240849414647',
    projectId: 'shipdetection-28c56',
    storageBucket: 'shipdetection-28c56.firebasestorage.app',
    iosBundleId: 'com.example.shipDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvvNqManYwho_dYQuNhKt_dhe1Wq5YPtk',
    appId: '1:240849414647:web:b5bcf2091e3b03d11ca6f2',
    messagingSenderId: '240849414647',
    projectId: 'shipdetection-28c56',
    authDomain: 'shipdetection-28c56.firebaseapp.com',
    storageBucket: 'shipdetection-28c56.firebasestorage.app',
    measurementId: 'G-Q6S7FVSZVK',
  );
}
